In [1]:
import pandas as pd
import numpy as np

In [13]:
df1=pd.read_csv("api_data_aadhar_enrolment_0_500000.csv")
df2=pd.read_csv("api_data_aadhar_enrolment_500000_1000000.csv")
df3=pd.read_csv("api_data_aadhar_enrolment_1000000_1006029.csv")

In [18]:
print("size of df1: ",df1.shape)
print("size of df2: ",df2.shape)
print("size of df3: ",df3.shape)

size of df1:  (500000, 7)
size of df2:  (500000, 7)
size of df3:  (6029, 7)

In [22]:
df_comb=pd.concat([df1,df2,df3], ignore_index=True)
df_comb

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,02-03-2025,Meghalaya,East Khasi Hills,793121,11,61,37
1,09-03-2025,Karnataka,Bengaluru Urban,560043,14,33,39
2,09-03-2025,Uttar Pradesh,Kanpur Nagar,208001,29,82,12
3,09-03-2025,Uttar Pradesh,Aligarh,202133,62,29,15
4,09-03-2025,Karnataka,Bengaluru Urban,560016,14,16,21
...,...,...,...,...,...,...,...
1006024,31-12-2025,West Bengal,West Midnapore,721149,2,0,0
1006025,31-12-2025,West Bengal,West Midnapore,721150,2,2,0
1006026,31-12-2025,West Bengal,West Midnapore,721305,0,1,0
1006027,31-12-2025,West Bengal,West Midnapore,721504,1,0,0
1006028,31-12-2025,West Bengal,West Midnapore,721517,2,1,0

In [23]:
df_comb['state']=df_comb['state'].str.strip().str.title()

In [24]:
df_comb.head()

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,02-03-2025,Meghalaya,East Khasi Hills,793121,11,61,37
1,09-03-2025,Karnataka,Bengaluru Urban,560043,14,33,39
2,09-03-2025,Uttar Pradesh,Kanpur Nagar,208001,29,82,12
3,09-03-2025,Uttar Pradesh,Aligarh,202133,62,29,15
4,09-03-2025,Karnataka,Bengaluru Urban,560016,14,16,21

In [25]:
df_comb['state'].value_counts()

state
Uttar Pradesh                                   110369
Tamil Nadu                                       92552
Maharashtra                                      77191
West Bengal                                      76530
Karnataka                                        70198
Andhra Pradesh                                   65663
Bihar                                            60567
Rajasthan                                        56159
Madhya Pradesh                                   50225
Gujarat                                          46624
Odisha                                           43692
Telangana                                        42774
Kerala                                           39145
Assam                                            31827
Jharkhand                                        23218
Punjab                                           20439
Chhattisgarh                                     18550
Haryana                                          15997
Jammu And Kashmir                                11316
Himachal Pradesh                                 10346
Uttarakhand                                      10007
Delhi                                             6804
Meghalaya                                         3771
Tripura                                           3729
Orissa                                            3319
Manipur                                           3218
Nagaland                                          1999
Arunachal Pradesh                                 1601
Goa                                               1527
Mizoram                                           1481
Puducherry                                        1042
Sikkim                                            1010
Chandigarh                                         859
Pondicherry                                        817
Ladakh                                             304
Andaman And Nicobar Islands                        289
Dadra And Nagar Haveli                             162
Lakshadweep                                        159
Jammu & Kashmir                                    139
Dadra And Nagar Haveli And Daman And Diu           116
Andaman & Nicobar Islands                          103
Daman And Diu                                       92
Dadra & Nagar Haveli                                24
100000                                              22
Daman & Diu                                         20
West  Bengal                                        15
West Bangal                                          9
Westbengal                                           7
The Dadra And Nagar Haveli And Daman And Diu         2
Name: count, dtype: int64

we see that UP has the state with the highest enrolment.

In [41]:
df_comb['district']=df_comb['district'].str.strip().str.title()

In [42]:
UP=df_comb[df_comb['state']=='Uttar Pradesh']
UP

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
2,09-03-2025,Uttar Pradesh,Kanpur Nagar,208001,29,82,12
3,09-03-2025,Uttar Pradesh,Aligarh,202133,62,29,15
7,09-03-2025,Uttar Pradesh,Bahraich,271865,26,60,14
8,09-03-2025,Uttar Pradesh,Firozabad,283204,28,26,10
10,09-03-2025,Uttar Pradesh,Maharajganj,273164,31,70,13
...,...,...,...,...,...,...,...
1005743,31-12-2025,Uttar Pradesh,Varanasi,221002,10,18,0
1005744,31-12-2025,Uttar Pradesh,Varanasi,221104,4,11,0
1005745,31-12-2025,Uttar Pradesh,Varanasi,221107,1,15,0
1005746,31-12-2025,Uttar Pradesh,Varanasi,221207,1,9,0
1005747,31-12-2025,Uttar Pradesh,Varanasi,221313,1,0,0

In [40]:
UP['district'].value_counts()

district
Azamgarh        2967
Lucknow         2933
Jaunpur         2689
Allahabad       2626
Kanpur Nagar    2601
                ...
Kushinagar *       6
Shravasti          4
Raebareli          2
Kushi Nagar        1
Bagpat             1
Name: count, Length: 89, dtype: int64

In UP, Azamargh has the highest enrolment.